{% set version = "0.0.1" %}

package:
  name: paged_html_theme
  version: {{ version }}

source:
  path: ../

build:
  number: 7
  noarch: python
  
  entry_points:
    

requirements:
  build:
    - python ==3.7.*
    - sphinx <3.0
    - click
    - libsass
   
  run:
    - python ==3.7.* 
    - sphinx <3.0
    - click
    - libsass

test:
  imports:
    - paged_html_theme

about:
  home: https://github.com/eoas-ubc/paged_html_theme
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'sphinx theme for pdf printing'
  description: |
    python_html_theme uses pagedjs to implement
    css3 @page media formatting

extra:
  recipe-maintainers:
    - phaustin
