name: buildit
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - runjb
  - click
  - sphinx=2.4.4
  - jupyter
  - pip
  - libsass
  - pip:
    - click_log
    - click_completion
    - git+https://github.com/phaustin/jupyter-sphinx.git
    - git+https://github.com/executablebooks/MyST-NB.git
    - git+https://github.com/mwouts/jupytext.git




