name: theme_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - python=3.7.*
  - jupyter
  - sphinx=2.4.4
  - ghp-import
  - pip
  - pip:
    - git+https://github.com/executablebooks/MyST-NB.git
    - jupyter-cache[cli]
    - git+https://github.com/mwouts/jupytext.git
    - git+https://github.com/phaustin/jupyter-sphinx.git@debug
    - git+https://github.com/readthedocs/sphinx_rtd_theme.git    
