name: theme_dev
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - git
  - runjb
  - python=3.7.*
  - jupyter
  - sphinx=2.4.4
  - ghp-import
  - numpy
  - pip
  - pip:
    - git+https://github.com/executablebooks/MyST-NB.git
    - git+https://github.com/eoas-ubc/paged_html_theme.git@release
    - jupyter-cache[cli]
    - git+https://github.com/mwouts/jupytext.git
    - git+https://github.com/phaustin/jupyter-sphinx.git
    - sphinx_rtd_theme
