# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Updates and checks out the release branch
    - name: Update/check out release branch
      run: |
        echo git fetch
        git fetch
        echo git branch -f release master
        git branch -f release master
        echo git checkout release
        git checkout release

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' 

    - name: Generate HTML with injected CSS
      run: python.exe inject_css.py

    - name: Add generated files and push
      run: |
        git status  
      # echo git push origin release --force
      # git push origin release --force
      
